account/urls.py
from django.conf.urls import patterns, url
from django.contrib.auth import views as auth_views
from django.views.generic import RedirectView
from account.views import profile, register

urlpatterns = patterns('',
    url(r'^login/', auth_views.login, name='login'),
    url(r'^register/', register, name='register'),
    url(r'^profile/', profile, name='profile'),
    url(r'^password_change/done/', RedirectView.as_view(
        url='/profile/'), name='password_change_done'),
    url(r'^logout/', auth_views.logout, name='logout'),
    url(r'^password_change/', auth_views.password_change, name='password_change'),
)

shold/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
from django.views.generic import RedirectView

admin.autodiscover()

urlpatterns = patterns('',
    url(r'^password_change/done/', RedirectView.as_view(
        url='/profile/'), name='password_change_done'),

    url(r'^admin/', include(admin.site.urls)),

    url(r'^accounts/', include('account.urls', namespace='account', app_name='account')),
    url(r'^villages/', include('village.urls', namespace='village', app_name='village')),
)

templates/base.html
{% load firstof from future %}<!DOCTYPE html>
<html lang="{{ LANGUAGE_CODE|default:"en-us" }}" {% if LANGUAGE_BIDI %}dir="rtl"{% endif %}>
<head>
    <title>{% block title %}{% endblock %}</title>
    {% block blockbots %}<meta name="robots" content="NONE,NOARCHIVE" />{% endblock %}
</head>
{% load i18n %}

<body class="{% if is_popup %}popup {% endif %}{% block bodyclass %}{% endblock %}">
    <!-- Container -->
    <div id="container">
        <!-- Header -->
        <div id="header">
            {% if user.is_active and user.is_staff %}
                <div id="user-tools">
                    {% trans 'Welcome,' %}
                    <strong>{% firstof user.get_short_name user.get_username %}</strong>.
                    {% block userlinks %}
                        {% if user.has_usable_password %}
                        <a href="{% url 'account:password_change' %}">{% trans 'Change password' %}</a> /
                        {% endif %}
                        <a href="{% url 'account:logout' %}">{% trans 'Log out' %}</a>
                    {% endblock %}
                </div>
            {% endif %}
            {% block nav-global %}{% endblock %}
        </div>
        <!-- END Header -->

        {% block messages %}
            {% if messages %}
                <ul class="messagelist">{% for message in messages %}
                    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message|capfirst }}</li>
                {% endfor %}</ul>
            {% endif %}
        {% endblock messages %}


        <!-- Content -->
        <div id="content" class="{% block coltype %}colM{% endblock %}">
            {% block pretitle %}{% endblock %}
            {% block content_title %}{% if title %}<h1>{{ title }}</h1>{% endif %}{% endblock %}
            {% block content %}
            {% block object-tools %}{% endblock %}
            {{ content }}
            {% endblock %}
            {% block sidebar %}{% endblock %}
            <br class="clear" />
        </div>
        <!-- END Content -->

    </div>
</body>

templates/base_site.html
{% extends "base.html" %}
{% load i18n %}